### ISSUE TITLE
Deinterlace node causing crash

### ISSUE THREAD

**Issue by nierymek** [MrKepzie/Natron#1078]
Bug reproduced on Windows 10, Yosemite and Ubuntu.

**Comment by olear** [comment]
Steps to reproduce?

Just adding the node on a image does not crash here, but the result seems wrong, changing the source combo box does however crash Natron.

**Comment by nierymek** [comment]
On Windows it crashed immediately after adding the node, on Yosemite and Ubuntu it shows bad result and crashes some time later. The error occures on Natron 2. On 1.2.1 it works great.

**Comment by devernay** [comment]
Issue is probably fixed by https://github.com/devernay/openfx-misc/commit/430238d4f3f8ec8682ff4113e7c636187687622b
Can you try one of the next snapshots and check?

**Comment by nierymek** [comment]
I'll check it tomorrow and let you know if it works

**Comment by nierymek** [comment]
I installed the latest snapshot and now it works properly. Thanks for your help!

**Comment by olear** [comment]
Still crashes if you change source combo box (tested on Mac/Linux).

**Comment by nierymek** [comment]
"Still crashes if you change source combo box (tested on Mac/Linux latest snapshot)."

The same on Windows

**Comment by MrKepzie** [comment]
Fixed in https://github.com/devernay/openfx-misc/commit/88ddbdfb2cb52907d037c13150f4cfb5cede281a
