### ISSUE TITLE
different behaviour when rendering in multiview

### ISSUE THREAD

**Issue by sozap** [MrKepzie/Natron#412]
I'm working on a multiview project, when I render the Right view the rendertime get very very long compared to the Left one. Also the RAM and CPU usage is quite different...
I've rendered each view in blender with separate image sequences for left and right views...
In natron each view is feetched to a join view node, and at the end of the tree I separate them with two OneView node.

One image in the Left view took ~9s to render , and in the right view it's around 12 minutes !!

also when rendering the right view the memory seems to keep increasing and swapping...

I'm using snapshots on Linux : d6df5bdffc7f094ea316a57d55b0441938772a56

**Comment by MrKepzie** [comment]
This might be a small bug indeed

**Comment by MrKepzie** [comment]
Can you show you node graph ? Are you experiencing issues with the Viewer or Writer ?

**Comment by sozap** [comment]
I guess it's with both, it's with the writer that I get the confimation that something is getting wrong... but the viewer seemed slow to me when working with a stereo output.

![capture du 2015-01-21 15 33 28](https://cloud.githubusercontent.com/assets/9614046/5837861/3f5aa3ee-a183-11e4-810d-a31a7c121726.png)

Here is my nodegraph, I just workarounded for the moment by using a switch node to render the RIGHT view, so don't pay attention to the nodes with linked values...

**Comment by MrKepzie** [comment]
https://github.com/MrKepzie/Natron/commit/ecd07337525dc633caab7a6e8afd40dcc5b5f592 should fix it

**Comment by sozap** [comment]
Nice ! I will test it for sure !
I still don"t get updates throught the maintenance tool, I guess you haven't fixed it yet... But once it's ok I'll tell you if I still found some issues .
thanks a lot , this fix is very welcome !

**Comment by MrKepzie** [comment]
updates are working: https://sourceforge.net/projects/natron/files/snapshots/linux64/repo/

Download 1 of the installer on this page. Note that the date is WRONG because the virtual machine's date is not up to date

**Comment by sozap** [comment]
great, I'll check it on monday, and will keep you informed !
thanks !

**Comment by sozap** [comment]
hum, sadly I still get the issue, with a fresh install
the render gets very slow when rendering the right view and the ram gets filled until Natron crash
here is a screen capture :
![capture du 2015-02-02 11 54 14](https://cloud.githubusercontent.com/assets/9614046/5999591/9b4d204c-aad3-11e4-8f9c-ba507f19a57d.png)

**Comment by MrKepzie** [comment]
I might need the project (without necessarily the images) because here every project that I attempt renders correctly

**Comment by sozap** [comment]
here is the file :

http://www.filebin.ca/1qQCsUEBaMMT/S02A_compo06.ntp

the natron version :

b96b4513dfd0168f824b7bb2bada81d0a27c38da


don't hesitate to tell me if I can do something else ...

2015-02-03 19:18 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> I might need the project (without necessarily the images) because here
> every project that I attempt renders correctly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/412#issuecomment-72704147>.
>



-- 
Paul Szajner
Infographiste 2D/3D
showreel : http://www.vimeo.com/11540026
mobile    : 06 27 16 26 89

**Comment by MrKepzie** [comment]
Which one is taking so much time ? WriteRIGHT ?

**Comment by MrKepzie** [comment]
Also note that you did not set the "Numbers of views” in the project settings to 2.

**Comment by sozap** [comment]
Hum sorry, I've sent you the file without thinking... :)

Set the node MV_HACK to 0 (that switch to multiview mode) and try to connect writeRIGHT to the node called RIGHT ( wich is a OneView node) and render it , the LEFT node is rendering correctly...

I'm trying to re-render with the correct number of views now but that doesn't seems to help, I'll do more test tomorrow...

Thanks for your time :)

**Comment by MrKepzie** [comment]
The Merge4 node is only connected to Crop1.1.1 is this normal ?
It makes just a sub-graph with very few nodes there must be a connection missing

**Comment by sozap** [comment]
Hum, yeah it's connected to a realsmart motion blur plugin : 
![capture du 2015-02-04 10 17 31](https://cloud.githubusercontent.com/assets/9614046/6037764/4362ec92-ac57-11e4-9e29-0a3c6a9a8731.png)
there is also another one used in the graph...

**Comment by MrKepzie** [comment]
There's indeed something slowing down the render which I fail to figure out.
A stereo workflow in Natron should be as follows:

- Setup your project for 2 views in the project settings
- Join 2 Readers with a JoinViews node
- do all the processing you want on all views downstream
- whenever you need to separate them, use the OneView node

To render, you can either use the OneView to separate the stream views, or just plug your Write node to the branch upstream and output files with a  %v or %V filename (indicating the view tag).

Note that the WriteFFMPEG node cannot output 2 views at the same time and will warn you that it uses only the "Main view" of the project that you can define in the project settings.

**Comment by sozap** [comment]
Ok , I'll keep on with my workaround to render each view separately without slowing down...
Also when I render one view with this graph the Ram get filled even with the Left view like in my second screenshot :S so I must render this shot by blocks of N frames, to prevent Natron from crashing.
This doesn't append with simplier graphs.

**Comment by MrKepzie** [comment]
Hi @sozap ,

Finally after debugging we  ended up concluding we need to move on to the multi-plane suite implementation to provide  a better solution for stereo workflows.
Keep your switch for now, but do not use the oneViews nodes. 
We will implement the multi-plane suite very soon in the workshop branch and you'll be able to test it out from the snapshots. I close this as this is not really an issue, but rather an unfinished feature.

**Comment by MrKepzie** [comment]
@sozap  Just to let you know I just fixed it in https://github.com/MrKepzie/Natron/commit/d4d44855eb6082961c9901acd215d4ddf8e3430a

In the same time we implement The Foundry multi-view/plane suite and we're also implementing it in the stereo plug-ins, it will make it much better.

**Comment by sozap** [comment]
Great news !

I'll check it soon, as I'm about to finish my stereo work in a few weeks...

Keep up the good work, Natron is improving so fast it's pure awesomeness !

**Comment by MrKepzie** [comment]
Thanks

So now you should just set the number of views of the project to 2 and use the JoinViews/OneViews like you used to.
No need to use any switch.
