### ISSUE TITLE
Read FFmpeg error

### ISSUE THREAD

**Issue by JanHus1** [MrKepzie/Natron#529]
Hello everyone.
I've been trying to composit a short video in Natron and plan to use a couple of .mov and .mp4 files. However, when I try to open them via the ReadFFmpeg node, an error shows up saying that Natron "couldn't load frame" and no footage shows up. What's weird is that this applies to all files I need to use, but an unrelated .mp4 file I loaded up for testing works perfectly. All the files that produce an error can be played in WMP, by the way. I'm using the latest snapshot, but I reverted to 1.2 and the problem stays. Rendering (even to .mov) works fine.

Any ideas on how to fix this? From what I read, there seem to be a couple of problems with the node but outright failure to read data seems to be new.

**Comment by MrKepzie** [comment]
Can you send us a sample to reproduce the bug ?

**Comment by JanHus1** [comment]
https://www.dropbox.com/s/m3ybx5y2cuduewv/Ink%20Drip%20in%20Water.mp4?dl=0
Here you go. I tried converting it to .avi and .wmv but it clearly has to do something with the file so that didn't work either. Blender and After Effects, however load it without any problems.

**Comment by MrKepzie** [comment]
I was not able to download the file sorry

**Comment by JanHus1** [comment]
That's weird, I can download it even ig i'm not logged in. Is the download button not working or do you receive an error?

**Comment by MrKepzie** [comment]
i am getting a 404 error on this url, file was moved or removed

**Comment by JanHus1** [comment]
Do these work? I uploaded it again. https://www.dropbox.com/s/0o0rbw5mj8tne00/fireworks_3_correct.mp4?dl=0 https://www.dropbox.com/sh/5msw2gw2lpx5ysk/AAAqnlEyG8c9zxF0z6sdQIega?dl=0 
As I said, I can download them even if i'm not logged in so you really should be able to do it.

**Comment by MrKepzie** [comment]
Your file reads fine here

**Comment by JanHus1** [comment]
Any ideas on what could cause that error? SOmething wrong with my PC?

**Comment by MrKepzie** [comment]
What version of Natron are you using ? Can you try using the snapshots ?

**Comment by KarstenHoehne** [comment]
I had started a duplicate of this error yesterday
https://github.com/MrKepzie/Natron/issues/542

Here a quick summary:
I tried to open some stockfootage (free from footagecrate.com):
Quicktime Container MPEG-4, PNG Video with Alpha Channel, No Sound

I tried to open it in several Versions of Natron:
Natron 1.2.1 Windwos 7 64 Bit:
ReadFFmpeg1 error: could not find video stream

Natron Snapshot Windows 7 64 Bit: same error as above

Natron 1.2.1 Ubuntu 12.04 32-Bit:
ReadFFmpeg1 error: The specified transform file 'Natron/share/OpenColorIO/blender/luts/rec709.spi1d' could not be loaded. Invalid 'From' Tag

The Ubuntu Error could just indicate a faulty installation, thoug i did not get any error message during the installation process

The Video File in Question opens just fine in Blender 2.73a, indicating that their version of FFMPEG seems to work.

**Comment by MrKepzie** [comment]
In the preferences of natron, make sure that in the "OpenColorIO" tab, you have the "Blender" configuration selected. Then restart Natron and try to open your file again.

**Comment by KarstenHoehne** [comment]
On all 3 versions of Natron, OPenCOlorIO config is set to "blender", yet the error stays the same.

**Comment by JanHus1** [comment]
I'm already using the latest snapshot (on windows 64bit) and OPenCOlorIO config is set to blender.

**Comment by MrKepzie** [comment]
Will test on windows

**Comment by MrKepzie** [comment]
Windows 7 64bit with snapshots of Natron 2.0, the video reads fine.

**Comment by KarstenHoehne** [comment]
WIndows 7 64-bit, Snapshot form 5 hours ago:
ReadFFMPEG Error: unable to find video stream.

Tried with several files from FootageCrate.com
All files can be opened in Blender 2.73 VSE

If it works for you it might be an issue with graphics card / drivers

Card: GeForce GT 545
Driver 347.52

Any known trouble with that?

**Comment by KarstenHoehne** [comment]
tried again a 64 Bit Windows 8 machine, can not open the file.

But I noticed Natron Page states at System Requirements that at least a resolution of 1280x1024 is required. All PC s i have tested a lower than required vertical resolution. Could this cause the error?

If so it would be nice of the software to warn users on startup that the will not be able to use Natron.

**Comment by MrKepzie** [comment]
It has nothing to do with graphic drivers or display size, this is a bug with the plug-in using FFmpeg. For some reason, I'm unable to reproduce the bug and all the files you guys send I can read them fine on snapshots of Natron 2

**Comment by MrKepzie** [comment]
@KarstenHoehne Are you able to read this file : https://www.dropbox.com/s/0o0rbw5mj8tne00/fireworks_3_correct.mp4?dl=0

**Comment by KarstenHoehne** [comment]
the file opens and plays back.
Maybe it is a problem with alpha channel in video. I can open some other videos from my computer that don't have alpha in them and they work.

Is there a debug mode that will show some more info about what is happening when running Natron on a windows machine?

**Comment by MrKepzie** [comment]
There’s no debug mode unless you compile Natron yourself unfortunately ;)
Can you send me a download link to a file with alpha in it that you’re unable to read ?For some reasons I can’t download from the website your linked above.

**Comment by KarstenHoehne** [comment]
https://www.dropbox.com/s/ycff5cxzc7q20nq/FOOTAGECRATE-MuzzleFlashSmokeyRifle.mov?dl=0

The site has a 2 free downloads per day limit for unregistered user. Unfortunately their DL counter seems to be a bit buggy

**Comment by MrKepzie** [comment]
There's indeed a bug with alpha files, the reader only expects RGB files. I'm fixing it

**Comment by MrKepzie** [comment]
This has been fixed and pushed to openfx-io. The snapshots should have the fix in ~1h or so, report when you have tested

**Comment by KarstenHoehne** [comment]
will do.
And thx for the work and time you invest into Natron.

**Comment by MrKepzie** [comment]
Can I close it ?

**Comment by KarstenHoehne** [comment]
Just downloaded the latest snapshot, the error message still appears. Tried the file I send you and several other files.

Sorry for not responding earlier, got caught up in  work

**Comment by MrKepzie** [comment]
I'm sorry but on the same platform I am able to read the file you sent me, are you sure you are using the good version of Natron ? What is the error message ?

**Comment by KarstenHoehne** [comment]
just downloaded from here:
http://sourceforge.net/projects/natron/files/snapshots/Windows64/

unzipped it, started natron, pressed "r" to add a reader node, choose the file  from my disc

readFFMpeg1 error: unable to find video stream

**Comment by devernay** [comment]
Just added support for reading RGBA videos: https://github.com/MrKepzie/openfx-io/commit/795d9ce75d71ff02ec2883eb037fc5f3ccda1274

Does it fix this issue?

**Comment by KarstenHoehne** [comment]
Just downloaded the latest snapshot.
Several file that I obtained from FootageCrate.com still don't open.

However some other Stock Footage Files with alpha channel that I have now open without problem. These files did not open before.

The difference between the the ones that open and the ones that don't seems to be the video codec:
Files that open: use RLE as encoding with RGBA color, inside a quicktime container
Files that don't open: PNG encodeing with RGBA color inside a quicktime container

**Comment by olear** [comment]
Does the files play/work in ffmpeg(ffplay) or mplayer?

**Comment by KarstenHoehne** [comment]
mplayer shows a short screen completlely green, but as mentioned before Blender opens the files just fine and Blender uses ffmpeg under the hood as well.

here is the ouput from mplayer after everything has been loaded:
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.34.100 (internal)
Selected video codec: [ffpng] vfm: ffmpeg (FFmpeg PNG)
==========================================================================
Audio: no sound
Starting playback...
Could not find matching colorspace - retrying with -vf scale...
Opening video filter: [scale]
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
[swscaler @ 00000000017ca180]bicubic scaler, from rgba to yuv420p using MMXEXT
VO: [directx] 1920x1080 => 1920x1080 Planar YV12
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [directx] 1920x1080 => 1920x1080 Planar YV12
V:   0.7   0/  0 107% 30%  0.0% 0 0


Exiting... (End of file)

**Comment by devernay** [comment]
@KarstenHoehne Can you please give a link to a file that doesn't open?
You can also use the "ffprobe" executable to check the format/codecs of a file.

**Comment by devernay** [comment]
@KarstenHoehne please send us a link to a file that doesn't open

**Comment by KarstenHoehne** [comment]
Sorry for not responding. Going through a tough time.

File is the as has been uploaded by me some time ago to dropbix:
https://www.dropbox.com/s/ycff5cxzc7q20nq/FOOTAGECRATE-MuzzleFlashSmokeyRifle.mov?dl=0

**Comment by devernay** [comment]
I can read that file (Quicktime using the PNG codec) OK with the latest Natron snapshot, which has the following ffmpeg versions:
FFmpeg versions (compiled with / running with):
libavformat 56.25.101 / 56.25.101
libavcodec 56.26.100 / 56.26.100
libavutil 54.20.100 / 54.20.100
libswscale 3.1.101 / 3.1.101

Can you please give more details (Natron version, ffmpeg versions from the "?" button of the ReadFFmpeg properties panel) ?

**Comment by devernay** [comment]
will close this bug if we don't get a reference to an actual non-working file

**Comment by MrKepzie** [comment]
I'm closing this, I have updated the ffmpeg binaries on Win64 with the latest version, full-featured (except libbluray). Please re-open a separate issue if you encounter any problem again
