### ISSUE TITLE
Problem with Mask Bleed Through During Render

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#740]
Hi...
I am using Natron version 2.0.0 commit 50382121c2a54991a9797ed2efdd3c0bde3b2715.
This is the same comp that I reported a bug where the masks where reopening incomplete.  The issue in this report is that the masks work perfectly in the viewer.  I checked the masks and they where all closed before and after the render.  The first frame renders perfectly but all subsequent frames are bad with mask bleedthrough.

![natron 2 0 0 bad masks setup](https://cloud.githubusercontent.com/assets/10405914/8559512/86d8b720-24db-11e5-86ea-16b3cf20d3b9.png)
![natron 2 0 0 bad masks frame 0001](https://cloud.githubusercontent.com/assets/10405914/8559514/913ad61c-24db-11e5-82d3-01b1a9baed76.png)
![natron 2 0 0 bad masks frame 0002](https://cloud.githubusercontent.com/assets/10405914/8559517/957716dc-24db-11e5-8609-9a3c19907912.png)

**Comment by MrKepzie** [comment]
I fixed a bug last week regarding this matter, could you update to a newer snapshot and report if it is not fixed ?

**Comment by OldSkoolVFX** [comment]
As of the following snapshot version:
http://repo.natronvfx.com/Natron-linux-x86-install-snapshot-64.tgz
This issue is NOT fixed and is still present.  The first frame renders perfect and all the subsequent frames continue to have mask bleed through.  The roto shapes are closed.  That bug has been fixed.

**Comment by MrKepzie** [comment]
I cannot reproduce the bug. Can you send me the project (without necessarily the input images)

**Comment by OldSkoolVFX** [comment]
I uploaded the file to my Dropbox.  See the link below:
https://www.dropbox.com/s/vr4z7r4502nme76/SC04_credit_roll_comp_05.ntp?dl=0
The issue also shows up in the viewer with the snapshot above.

**Comment by OldSkoolVFX** [comment]
Have you had any luck figuring this issue out yet?

**Comment by devernay** [comment]
Reopening, targetting for 2.0.

**Comment by MrKepzie** [comment]
Honestly I could not reproduce the bug here

**Comment by devernay** [comment]
@OldSkoolVFX can you help us reproduce the issue?
Make sure you don't have old plugins in /usr/OFX (on linux)

**Comment by OldSkoolVFX** [comment]
**> Make sure you don't have old plugins in /usr/OFX (on linux)**
I don't have a *'/usr/OFX/'* directory since there are no .DEB files.  I locally install Natron in my home directory and totally replace each install with the new one.  I do use all the plugins.

**> can you help us reproduce the issue?**
I tried to Install the newest snapshot:
*Natron_Linux_bundle_snapshot_x86-64bit.tgz / 2015-07-15 / 93.2 MB*
But again as I reported in another bug report I can't open Natron on my system.
I reported this already in *'Natron crashes on startup - splash screen only #744'* only I don't even get a splash screen now.  This snapshot version:
*'http://repo.natronvfx.com/Natron-linux-x86-install-snapshot-64.tgz' from 07/13/2015*
Has the same issue.  What else can I do to help you?

**Comment by olear** [comment]
http://downloads.natron.fr/Linux/snapshots/64bit/files/Natron-latest-Linux-x86_64bit-snapshot.tgz

We are currently busy getting Natron and plugins up-to-date on all platforms.

**Comment by OldSkoolVFX** [comment]
I used the snapshot supplied above which loaded just fine in Ubuntu 14.04 but still produced the same masking error.  Tell me what steps you might want me to do to help resolve this.

**Comment by MrKepzie** [comment]
Could you send me the input images (or a cut of it) also ? I fail to reproduce the bug with just Radials instead

**Comment by MrKepzie** [comment]
Also a screencast of the exact steps you are doing to reproduce the bug: like how you are starting the render, how many threads are in the preferences, etc...

**Comment by OldSkoolVFX** [comment]
Thank you for pursuing this issue.
Here are the requested components:

**The Natron file:**
https://www.dropbox.com/s/vr4z7r4502nme76/SC04_credit_roll_comp_05.ntp?dl=0

**The image for *Repainted BG* Reader node:**
https://www.dropbox.com/s/2muqj9sgv8xeouy/CreditsBG_02_2630_Repaint.png?dl=0

**The video for *Live 135DO* Reader node:**
https://www.dropbox.com/s/gl6kttgqwkzubjq/SC03_CIMG0153_DO.AVI?dl=0
**_(Please et me know you have this so I can delete it from Dropbox to save space.)_**

*> "I fail to reproduce the bug with just Radials instead"*
I really don't know what this is.  Dummy images?

*> "the exact steps you are doing to reproduce the bug"*
I reproduced where in the nograph the bug is coming from.  See the section labled *'Location of the node causing the issue in the nodegraph'* and the accompanying images below.  There is a rectangle "mask" being used that is not in the nodegraph.  So it seems to be something going on in this .NTP file.  Also I can't think of why a mask would pop on after the first frame.  I have no time nodes in the nodegraph so I would expect all the masks to be persistent across the duration of the the project.

I have tried to eliminate it by rearranging nodes and pipes i.e. recomp it in a different manner.   This has been unsuccessful.  From what I gather this node setup does what it's supposed to do on your system but not on mine.

BTW this has happened on two different laptops on my end.  One with an AMD GPU and one with an Intel GPU.  Both use Ubuntu 14.04 running on i7 processors.  The AMD's CPUs is the 1st generation and the Intel's is a 4th generation.  Both are quad core i7s.  Maybe it's an Ububtu/linux thing?

*> "how many threads are in the preferences"*
In the preferences *'max threads usable per effect'* is set to 0 or "guess".

*> "how you are starting the render"*
As to how I start the render, I press the *'Render'* button in the Writer node once I connect it.  The first frame renders fine the rest all have the mask "bleed through".

I have noted that there were issues in other node setups in 1.2.1 that if I had sequential masks they would not render properly and the later masks would not be present.  It was like it could not parse how to order or deal with the additional masks in the setup.  I got around this by pre-comping or moving the project to Blender just as I moved this shot to Blender so I could complete the project.

**Location of the node causing the issue in the nodegraph**
I did however isolate the masks after I wrote the comment earlier about multiple masks not working.

I isolated each mask and one combo mask and isolated the issue to the first mask merge (merge2 plus).  The purpose of this node is to double the exposure of the sign in the ground to make it more visible.  There appears to be a rectangle mask(?) that pops on at frame 2 and stays.  This is not in the nodegraph as in I did not put any rectangle mask into the nodegraph.  There is only one bezier shape in the roto node and there is only one roto node.  See the Images below:

Below is the original base node setup.
![iso 01 original node setup](https://cloud.githubusercontent.com/assets/10405914/8990070/f96da662-36bd-11e5-97ee-93fdbfbd0aeb.png)
Below is the sign isolated to the first merge node (Merge2 plus).  **This is where the issue is.**
![iso 02 sign roto 1 failed nodes](https://cloud.githubusercontent.com/assets/10405914/8990068/f96bc7ac-36bd-11e5-9c2a-1e8fa9f0b7e3.png)
Below is the sign isolated to the first merge node (Merge2 plus) frame 1 render. It is good.
![iso 02 sign roto 1 failed render 01](https://cloud.githubusercontent.com/assets/10405914/8990073/f9704804-36bd-11e5-8ab8-d708ab62899b.png)
Below is the sign isolated to the first merge node (Merge2 plus) frame 2 render. It and every following frame are bad. **Notice the rectangle.**  I do not have a rectangle mask in the nodegraph.  I used an articulated roto.  So where is the rectangle coming from?  This appears to be the underlying issue!
![iso 02 sign roto 1 failed render 02](https://cloud.githubusercontent.com/assets/10405914/8990069/f96cccd8-36bd-11e5-9f82-853b978060d5.png)
Below is the sign isolated up to the second merge node (Merge3 over).  It also renders bad probably due to the output of the merge2 node.
![iso 03 sign roto 2 failed](https://cloud.githubusercontent.com/assets/10405914/8990071/f96f9774-36bd-11e5-8816-fa45bce80f28.png)

**All the following render good when isolated.**
![iso 04 box mask success](https://cloud.githubusercontent.com/assets/10405914/8990074/f970a970-36bd-11e5-9259-f806997c3f4b.png)
![iso 05 igor roto success](https://cloud.githubusercontent.com/assets/10405914/8990076/f979959e-36bd-11e5-8106-7cb6286bbab3.png)
![iso 06 no sign mask success](https://cloud.githubusercontent.com/assets/10405914/8990077/f97a39c2-36bd-11e5-87dd-565c8ce387fc.png)

I hope this helps.  Thanks.

**Comment by MrKepzie** [comment]
Okay thanks, it appears to be https://github.com/MrKepzie/Natron/issues/786 . I'm still trying to resolve this

**Comment by OldSkoolVFX** [comment]
OK, good luck resolving this.
Thanks.

**Comment by devernay** [comment]
now that #786 is fixed, is this one resolved too?

**Comment by OldSkoolVFX** [comment]
As of commit 6652abf58d027a2b5710d19a53ceb63e493a7376 from Aug 3 (downloaded and installed this morning), no.

**Comment by olear** [comment]
You need a newer snapshot, try this https://downloads.natron.fr/~olear/Natron/Natron-1d08991f7a2e24d086881c29b638461dd9db846e-Linux-x86_64bit.tgz until the build server is up-and-running

**Comment by OldSkoolVFX** [comment]
devernay and olear - I used the newer snapshot above and it still has the same problem.  The first frame fine and in all following there is mask bleed through so no it is not resolved yet.

**Comment by MrKepzie** [comment]
Hmm there’s no bug left in roto as far as I see it, I guess the “bleeding” comes from the Merge operations you are using, I get the same results for all frames on my end with your project

**Comment by OldSkoolVFX** [comment]
That really is a bummer. I don't know if this helps but I sometimes get this warning:

![warning](https://cloud.githubusercontent.com/assets/10405914/9214980/80eccb3c-4072-11e5-9803-319241156d50.png)

This occurs when I turn the mask color from black to white (1,1,1).  Why it has a fit when I change the color I don't know. Also the warning stays for a bit even if I change the color back.  Whe warning mentions a box and gives location and size info. I did't put any "box" in the roto node so unless it's "under the hood" so to speak as in inside the code of the node which you cant' find.  II mention this because maybe that relates to the issue because the bled is outside of a box that again I have no idea where it came from.

**Comment by MrKepzie** [comment]
Indeed this NaN issue is a bug in the Roto
